#!/usr/bin/with-contenv bash

PUID=${PUID:-1000}
PGID=${PGID:-1000}
USER=${USER:-dev}

# change UID/GID if not same as specified in docker-compose.yml
groupmod -o -g "${PGID}" ${USER}
usermod -o -u "${PUID}" ${USER}
usermod -d /home/${USER} ${USER}

# TODO: set to use sudo without password when user not exists in /etc/sudoers & /etc/sudoers.d/
#if ! grep -q "${USER}" /etc/sudoers; then
#    echo "${USER} ALL=(ALL:ALL) NOPASSWD:ALL" > /etc/sudoers.d/${USER}
#    chmod 0440 /etc/sudoers.d/${USER}
#fi

echo '
-------------------------------------
    _   __      __  __      _                
   / | / /___  / / / /___  (_)___ ___  _____ 
  /  |/ / __ \/ / / / __ \/ / __ `/ / / / _ \
 / /|  / /_/ / /_/ / / / / / /_/ / /_/ /  __/
/_/ |_/\____/\____/_/ /_/_/\__, /\__,_/\___/ 
                             /_/             
-------------------------------------
GID/UID
-------------------------------------'
echo "
User uid:    $(id -u ${USER})
User gid:    $(id -g ${USER})
-------------------------------------
"
cp /root/.bashrc /home/${USER}/
cp /root/.vimrc /home/${USER}/
chown ${USER}:${USER} /home/${USER}
